<?php
// Always start with the headers. The blank line after is crucial.
setcookie("user_name", "Ahmed", time() + 3600, "/");
setcookie("user_age", "30", time() + 3600, "/");

header("Content-Type: text/html");
header("Status: 200 OK");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CGI Test Page</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background-color: #f4f4f9; }
        .container { max-width: 800px; margin: auto; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        h1, h2 { color: #333; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #eee; }
        th { background-color: #f8f8f8; }
        code { background-color: #eef; padding: 2px 5px; border-radius: 4px; }
        .method-box { padding: 15px; margin-top: 15px; border-radius: 5px; }
        .get { background-color: #e7f3ff; border-left: 5px solid #007bff; }
        .post { background-color: #e8f5e9; border-left: 5px solid #28a745; }
        .no-data { color: #888; }
    </style>
</head>
<body>

<div class="container">
    <h1>✅ CGI Script Executed Successfully!</h1>
    <p>This page is generated by a PHP script. If you can see it, your Webserv is correctly executing CGI.</p>

    <h2>Request Method</h2>
    <p>The request method was: <code><?php echo htmlspecialchars($_SERVER['REQUEST_METHOD']); ?></code></p>

    <!-- Display GET Data -->
    <?php if ($_SERVER['REQUEST_METHOD'] == 'GET'): ?>
        <div class="method-box get">
            <h3>GET Data (Query String)</h3>
            <?php if (!empty($_SERVER['QUERY_STRING'])): ?>
                <code><?php echo htmlspecialchars($_SERVER['QUERY_STRING']); ?></code>
            <?php else: ?>
                <p class="no-data">No GET data was sent.</p>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <!-- Display POST Data -->
    <?php if ($_SERVER['REQUEST_METHOD'] == 'POST'): ?>
        <div class="method-box post">
            <h3>POST Data (Request Body)</h3>
            <?php 
                $post_body = file_get_contents('php://input');
                if (!empty($post_body)):
            ?>
                <code><?php echo htmlspecialchars($post_body); ?></code>
            <?php else: ?>
                <p class="no-data">No POST data was sent.</p>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <h2>Cookies Received by the Script</h2>
    <table>
        <tr><th>Cookie Name</th><th>Value</th></tr>
        <?php if (!empty($_COOKIE)): ?>
            <?php foreach ($_COOKIE as $name => $value): ?>
                <tr>
                    <td><code><?php echo htmlspecialchars($name); ?></code></td>
                    <td><code><?php echo htmlspecialchars($value); ?></code></td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr><td colspan="2" class="no-data">No cookies were sent with this request.</td></tr>
        <?php endif; ?>
    </table>

    <h2>Key CGI Environment Variables</h2>
    <table>
        <tr><th>Variable Name</th><th>Value</th></tr>
        <?php
            $cgi_vars = array(
                'SERVER_SOFTWARE', 'SERVER_NAME', 'GATEWAY_INTERFACE',
                'SERVER_PROTOCOL', 'SERVER_PORT', 'REQUEST_METHOD',
                'PATH_INFO', 'PATH_TRANSLATED', 'SCRIPT_NAME', 'SCRIPT_FILENAME',
                'QUERY_STRING', 'REMOTE_ADDR', 'CONTENT_TYPE', 'CONTENT_LENGTH',
                'HTTP_USER_AGENT', 'HTTP_COOKIE'
            );
            foreach ($cgi_vars as $var) {
                echo "<tr>";
                echo "<td><code>" . htmlspecialchars($var) . "</code></td>";
                echo "<td><code>" . (isset($_SERVER[$var]) ? htmlspecialchars($_SERVER[$var]) : '[Not Set]') . "</code></td>";
                echo "</tr>";
            }
        ?>
    </table>
</div>

</body>
</html>